baseURL = "/"
languageCode = "en-us"
title = "Amazon Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
[params]
    subtitle = "amazon"
    subsite = "amazon"
    description = "Collaborative analysis on shopping experience and personalization algorithm"
    tagline = "Algorithms should be under users control; Watch what they do on a shopping experience"

[permalinks]
    posts = "/:slug/"

[menu]
 [[menu.main]]
    page = "Tracking Exposed"
    identifier = "trex"
    name = "Umbrella project: Tracking Exposed"
    url = "https://tracking.exposed"
    weight = 90


 [[menu.featured]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
    post = "This prototype works but is undocumented and supposedly only for researchers. It is not yet suitable for general use."
