baseURL = "/"
languageCode = "en-us"
title = "Amazon Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
[params]
    subtitle = "amazon"
    subsite = "amazon"
    description = "Collaborative analysis on shopping experience and personalization algorithm"
    tagline = "Algorithms should be under users control; Watch what they do on a shopping experience"

[permalinks]
    posts = "/:slug/"

[menu]
 [[menu.main]]
    page = ""
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
 [[menu.main]]
    page = "Project analysis"
    identifier = "background"
    name = "Project analysis"
    url = "/project-analysis/"
    weight = 10

 [[menu.featured]]
    name = "Algorithm Domination"
    url = "/submission"
    weight = -100
    pre = "/images/algorithmdom.svg"
    post = "Some of your data and what your master wants you to masturbate on today"
 [[menu.featured]]
    page = "compare"
    identifier = "compare"
    name = "Public Shame"
    url = "/compare"
    weight = -90
    pre = "/images/compare.svg"
    post = "Compare and measure your personalized recommandations and get a rough punishment"
 [[menu.featured]]
    page = "pov"
    identifier = "pov"
    name = "Behind the Scenes"
    url = "/pov"
    weight = -80
    pre = "/images/pov.svg"
    post = "See through our POV and play hard with our pleasure tools"

[[menu.footer]]
   page = "Tracking Exposed"
   identifier = "trex"
   name = "Umbrella project: Tracking Exposed"
   url = "https://tracking.exposed"
   weight = 90
