baseURL = "/"
languageCode = "en-us"
title = "Amazon Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
[params]
    subtitle = "amazon"
    subsite = "amazon"
    description = "Collaborative analysis on shopping experience and personalization algorithm"
    tagline = "Algorithms should be under users control; Watch what they do on a shopping experience"

[permalinks]
    posts = "/:slug/"

[menu]
 [[menu.main]]
    page = "Tracking Exposed"
    identifier = "trex"
    name = "Umbrella project: Tracking Exposed"
    url = "https://tracking.exposed"
    weight = 90
 [[menu.main]]
    page = "About"
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 80

 [[menu.featured]]
    identifier = "First results"
    name = "First results"
    url = "/first-results/"
    pre = "/images/amazon-spy-wired.png"
    weight = 20
    post = "This tool allow research to keep evidence on how Amazon personalize the shopping experience. Read more on our preliminary findings."
